const fs = require("fs");
const p = "c:/Users/user/Documents/americo_magumba/Construvasco/app/construvasco_laravel_v1/tools/bloco2_smoke_browser.mjs";
let s = fs.readFileSync(p, "utf8");
const start = s.indexOf("    await page.locator('input[formcontrolname=\"title\"]').fill");
const end = s.indexOf("    log('4. Wizard passos 1-3'");
if (start === -1) throw new Error('start');
const block = `    const projectStep = page.locator('app-wizard-step-project');
    await projectStep.locator('input[formcontrolname="title"]').fill('Casa Teste Bloco2 Smoke');
    await projectStep.locator('mat-select[formcontrolname="project_type"]').click();
    await page.locator('mat-option').filter({ hasText: 'Residencial' }).first().click();
    await projectStep.locator('mat-select[formcontrolname="tipologia"]').click();
    await page.locator('mat-option').filter({ hasText: 'T3' }).first().click();
    await page.click('button:has-text("Seguinte")');
    const briefingStep = page.locator('app-wizard-step-briefing');
    await page.waitForSelector('app-wizard-step-briefing', { timeout: 10000 });
    await briefingStep.locator('input[formcontrolname="localizacao"]').fill('Maputo, Costa do Sol');
    await briefingStep.locator('input[formcontrolname="area_m2"]').fill('180');
    await briefingStep.locator('input[formcontrolname="num_pisos"]').fill('2');
    await briefingStep.locator('mat-select[formcontrolname="estilo_arquitectonico"]').click();
    await page.locator('mat-option').first().click();
    await briefingStep.locator('mat-select[formcontrolname="paleta_acabamento"]').click();
    await page.locator('mat-option').first().click();
    await page.click('button:has-text("Seguinte")');
    await page.waitForSelector('app-wizard-step-references', { timeout: 10000 });
    await page.click('button:has-text("Seguinte")');
    await page.waitForSelector('app-studio-workspace', { timeout: 15000 });
    `;
s = s.slice(0, start) + block + s.slice(end);
fs.writeFileSync(p, s, "utf8");
